### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by nuest** [arturluizbr/docker-pkp-ojs#2]
Hi!
I've been extending your work, but that's not really feasible without knowing that you are actually OK with that :-)

Would you add an open source license to your project?

Are you interested in PRs with new features and to collaborate, or was is this not an active project of yours anymore?

**Comment by arturluizbr** [comment]
I'm ok with that.

Don't worry ^^

**Comment by arturluizbr** [comment]
@nuest, I'm not sure if I added correctly the license, first time adding on a github project ^^

Anyway i put there the MIT license, so you can do anything you want =D
